name: Rust

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - stable
          - beta
          - nightly

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Set up Rust
        run: rustup update ${{ matrix.toolchain }} && rustup default ${{ matrix.toolchain }}
      
      - name: Build
        run: |
          cargo build --verbose

      - name: Test subcommands
        run: |
          cargo run -- status -f tests/test_status.txt
          cargo run -- takeover -j tests/signatures_full.json -f tests/test_takeover.txt
          cargo run -- fuzz  -p tests/test_fuzzing.txt -u https://pwnwriter.xyz/FUZZ
          cargo run -- rdns -f tests/test_rdns.txt
